// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuY7W-6nTc5MmTiqjPbPV762ZFmg2ZnJQ',
    appId: '1:197175313012:web:e0a0a42d1fccd9f82ac721',
    messagingSenderId: '197175313012',
    projectId: 'testproject-79c3e',
    authDomain: 'testproject-79c3e.firebaseapp.com',
    storageBucket: 'testproject-79c3e.appspot.com',
    measurementId: 'G-XSDFDX7HDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsCueHYXy1on3EMyPKX8mjf7LRewUZh1U',
    appId: '1:197175313012:android:059fbf9091ad200c2ac721',
    messagingSenderId: '197175313012',
    projectId: 'testproject-79c3e',
    storageBucket: 'testproject-79c3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7eR5crJ40L3f5-Ts0cflxaTHGXbcHJA4',
    appId: '1:197175313012:ios:9fdfc52e26a5b4032ac721',
    messagingSenderId: '197175313012',
    projectId: 'testproject-79c3e',
    storageBucket: 'testproject-79c3e.appspot.com',
    iosBundleId: 'com.example.maalyAlkhayrTestProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7eR5crJ40L3f5-Ts0cflxaTHGXbcHJA4',
    appId: '1:197175313012:ios:8c4b8f5ede1181cd2ac721',
    messagingSenderId: '197175313012',
    projectId: 'testproject-79c3e',
    storageBucket: 'testproject-79c3e.appspot.com',
    iosBundleId: 'com.example.maalyAlkhayrTestProject.RunnerTests',
  );
}
